services:

  postgres:
    image: postgres:16
    container_name: devops-postgres

    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: devopsuser
      POSTGRES_PASSWORD: devopspassword

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: